
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const looks={casual:1,minimal:4,mode:8,feminine:5},names={casual:'CASUAL',minimal:'MINIMAL',mode:'MODE',feminine:'FEMININE'},signs={aries:'♈',taurus:'♉',gemini:'♊',cancer:'♋',leo:'♌',virgo:'♍',libra:'♎',scorpio:'♏',sagittarius:'♐',capricorn:'♑',aquarius:'♒',pisces:'♓'};let state={lat:35.6762,lon:139.6503,name:'Tokyo, Japan',weather:null};
function label(c){if(c===0)return['晴れ','☀️'];if([1,2].includes(c))return['晴れ時々くもり','🌤️'];if(c===3)return['くもり','☁️'];if([61,63,65,80,81,82].includes(c))return['雨','🌧️'];if([71,73,75,85,86].includes(c))return['雪','🌨️'];if([95,96,99].includes(c))return['雷雨','⛈️'];return['くもり','☁️']}
function setLook(feels=22){let style=$('#style').value,look=looks[style];$('#tag').textContent=names[style]+' / TODAY';let el=$('#figure');el.style.backgroundImage=`url(looks/look-${look}.webp)`;$('#figure').classList.add('changing');setTimeout(()=>$('#figure').classList.remove('changing'),120);$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.style===style))}
function outfit(feels,rain,wind){let a=feels;if($('#cold').value==='cold')a-=2;if($('#cold').value==='hot')a+=2;let t,r;if(a>=30){t='涼しいトップスで軽く';r='かなり暑め。通気性と日差し対策を優先。'}else if(a>=25){t='半袖＋軽い羽織';r='日中は半袖で快適。冷房対策に薄手の羽織を。'}else if(a>=20){t='長袖シャツがちょうどいい';r='脱ぎ着しやすい一枚が今日の正解。'}else if(a>=15){t='薄手ニット＋ジャケット';r='風があるとひんやり。軽い上着が安心。'}else{t='アウターをしっかり';r='冷え込み対策を優先。'}if(wind>=8)r+=' 風も強め。';if(rain>=50)r+=' 雨に強い靴が◎。';return[t,r]}
function render(d){state.weather=d;let c=d.current,x=d.daily,r=x.precipitation_probability_max[0]??0,[w]=label(c.weather_code),[ot,or]=outfit(c.apparent_temperature,r,c.wind_speed_10m/3.6);$('#temp').textContent=Math.round(c.temperature_2m);$('#cond').textContent=w;$('#rain').textContent=$('#rain2').textContent=r+'%';$('#wind').textContent=(c.wind_speed_10m/3.6).toFixed(1)+' m/s';$('#feels').textContent=Math.round(c.apparent_temperature)+'°C';$('#uv').textContent=x.uv_index_max?.[0]?.toFixed(1)??'--';$('#uvLabel').textContent=(x.uv_index_max?.[0]??0)>=6?'High':(x.uv_index_max?.[0]??0)>=3?'Moderate':'Low';$('#humidity').textContent=(c.relative_humidity_2m??'--')+'%';$('#place').textContent=state.name;$('#outShort').textContent=$('#outTitle').textContent=ot;$('#outReason').textContent=or;$('#note').textContent=`最高 ${Math.round(x.temperature_2m_max[0])}° / 最低 ${Math.round(x.temperature_2m_min[0])}°。${r>=50?'雨に合わせて移動は少し余裕を。':'大きな雨の心配は少なめ。'}`;if(r>=60){$('#umbrellaText').textContent='傘、持ってこ ☂';$('#umbrellaSub').textContent='今日はしっかり雨対策。'}else if(r>=30){$('#umbrellaText').textContent='折りたたみ傘が安心';$('#umbrellaSub').textContent='にわか雨に備えよう。'}else{$('#umbrellaText').textContent='傘なしでOK';$('#umbrellaSub').textContent='身軽にいけそう。'}setLook(c.apparent_temperature);hourly(d)}
function hourly(d){let h=d.hourly,n=new Date(),s=h.time.findIndex(v=>new Date(v)>=new Date(n.getFullYear(),n.getMonth(),n.getDate(),n.getHours()));if(s<0)s=0;$('#hourly').innerHTML=h.time.slice(s,s+5).map((v,j)=>{let i=s+j,t=new Date(v);return`<div class="hour"><small>${j?' '+t.getHours()+'時':'Now'}</small><i>${label(h.weather_code[i])[1]}</i><b>${Math.round(h.temperature_2m[i])}°</b></div>`}).join('')}
async function fetchWeather(){try{let u=`https://api.open-meteo.com/v1/forecast?latitude=${state.lat}&longitude=${state.lon}&current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m&hourly=temperature_2m,weather_code,precipitation_probability&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,uv_index_max&timezone=auto&forecast_days=2`,r=await fetch(u);render(await r.json())}catch{$('#cond').textContent='天気を取得できませんでした'}}
async function reverse(lat,lon){try{let r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lon}&zoom=10&accept-language=ja`),d=await r.json();return d.address?.city||d.address?.ward||d.address?.town||d.address?.state||'現在地'}catch{return'現在地'}}
function locate(){navigator.geolocation?.getCurrentPosition(async p=>{state.lat=p.coords.latitude;state.lon=p.coords.longitude;state.name=await reverse(state.lat,state.lon);fetchWeather()},()=>{})}
function fortune(){let s=$('#sign').value,d=new Date(),k=(d.getFullYear()*372+d.getMonth()*31+d.getDate()+s.length*17)%5,ts=['軽く動くほど運がひらく日。','小さな違和感がヒントの日。','寄り道に発見がありそう。','人より自分のペースが正解。','いつもと違う色を選んでみて。'],tx=['考えすぎる前の一歩がちょうどええ。','気になったものを一枚写真に残すと、あとでつながりそう。','帰り道を少し変えるだけで気分が切り替わるで。','予定を詰めすぎず、余白を残すと調子が出そう。','服か小物に一色だけ遊びを入れると気分も上向き。'];$('#fortuneTitle').textContent=ts[k];$('#fortuneText').textContent=tx[k];$('#fortuneSymbol').textContent=signs[s]}
function active(style){$('#style').value=style;setLook(state.weather?.current?.apparent_temperature??22)}function load(){try{let p=JSON.parse(localStorage.getItem('soramoPrefs'));if(p){$('#sign').value=p.sign||'libra';$('#cold').value=p.cold||'normal';$('#style').value=p.style||'casual'}}catch{}active($('#style').value);fortune()}function save(){localStorage.setItem('soramoPrefs',JSON.stringify({sign:$('#sign').value,cold:$('#cold').value,style:$('#style').value}));fortune();state.weather&&render(state.weather);let t=$('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
$$('.tab').forEach(b=>b.onclick=()=>active(b.dataset.style));$('#style').onchange=()=>active($('#style').value);$('#sign').onchange=fortune;$('#cold').onchange=()=>state.weather&&render(state.weather);$('#save').onclick=save;$('#locate').onclick=locate;$('#settingsJump').onclick=()=>$('#prefs').scrollIntoView({behavior:'smooth'});$('#date').textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(new Date());load();fetchWeather();
